

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import newpackage.connectivity;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mr._Guru
 */
public class entry extends javax.swing.JFrame {
    static boolean cont=false;

    /**
     * Creates new form entry
     */
    public entry() {this.setTitle("Profile");
        initComponents();
        setLocation(connectivity.getx(531),connectivity.gety(583));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(548, 620));
        setPreferredSize(new java.awt.Dimension(548, 620));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(14, 0, 505, 42);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setText("Vehicle");
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel6.setText("Vehicle No :");

        jLabel7.setText("Vehicle Type :");

        jTextField4.setEnabled(false);

        jLabel8.setText("Status : ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("In");
        jRadioButton1.setOpaque(false);

        jLabel2.setText("UID :");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Out");
        jRadioButton2.setOpaque(false);

        jLabel3.setText("Name :");

        jLabel4.setText("Remarks :");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bicycle", "Scooter", "MotorCycle", "Car", "Truck", "Other" }));
        jComboBox1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(12, 47, 523, 470);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Close");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEtchedBorder()));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 520, 110, 29);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEtchedBorder()));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 520, 120, 29);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -10, 530, 1100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        // TODO add your handling code here:
      
        
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(cont==false)
      {
          cont=true;
          jComboBox1.setEnabled(true);
          jTextField4.setEnabled(true);
      }
      else
          if(cont==true)
          {
              cont=false;
          jComboBox1.setEnabled(false);
          jTextField4.setEnabled(false);
          }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        Connection con=null;
 Statement stmt=null;
 ResultSet rs=null;
 String a[]=connectivity.file();
 String uid=a[1],pass=a[2];
                    String url="jdbc:mysql://localhost:"+a[0];
                   
        
        
       String id=jTextField1.getText();
       if(id.charAt(0)=='w'||id.charAt(0)=='W')
       {
            try{
                con=DriverManager.getConnection(url,uid,pass);
               stmt=con.createStatement();
               stmt.executeQuery("use ssm1");
                    rs=stmt.executeQuery("select * from worker where id='"+id+"'");
                   
                    while(rs.next()){
                      
                      
                        jTextField1.setText(rs.getString(1));
                        jTextField2.setText(rs.getString(2));
                        boolean s=false;
                        if(rs.getBoolean(11)==true){
                            jCheckBox1.setSelected(true);
                            jComboBox1.setEnabled(true);
                            jTextField4.setEnabled(true);
                       int status=rs.getInt(10); 
                       jComboBox1.setSelectedIndex(status);
                        jTextField4.setText(rs.getString(4));
                      
                        
                        }  if(rs.getBoolean(7)==false)
                            jRadioButton2.setSelected(true);
                        else
                            jRadioButton1.setSelected(true);
                        
                        byte[] image=rs.getBytes(8);
                      ImageIcon image1=new ImageIcon(image);
                      Image im=image1.getImage();
                      Image myImg=im.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(),Image.SCALE_SMOOTH);
                      ImageIcon newImage=new ImageIcon(myImg);
                      jLabel5.setIcon(newImage);
                    }}
                    catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
       }
       else
           if(id.charAt(0)=='V'||id.charAt(0)=='v')
           {
                try{
                con=DriverManager.getConnection(url,uid,pass);
               stmt=con.createStatement();
               stmt.executeQuery("use ssm1");
                    rs=stmt.executeQuery("select * from visitor where id='"+id+"';");
                   
                    while(rs.next()){
                          jTextField1.setText(rs.getString(1));
                        jTextField2.setText(rs.getString(2));
                        boolean s=false;
                        if(rs.getBoolean(10)==true){
                            jCheckBox1.setSelected(true);
                            jComboBox1.setEnabled(true);
                            jTextField4.setEnabled(true);
                       int status=rs.getInt(11); 
                       jComboBox1.setSelectedIndex(status);
                        jTextField4.setText(rs.getString(12));
                      
                        
                        }  if(rs.getBoolean(13)==false)
                            jRadioButton2.setSelected(true);
                        else
                            jRadioButton1.setSelected(true);
                    
                        byte[] image=rs.getBytes(14);
                      ImageIcon image1=new ImageIcon(image);
                      Image im=image1.getImage();
                      Image myImg=im.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(),Image.SCALE_SMOOTH);
                      ImageIcon newImage=new ImageIcon(myImg);
                      jLabel5.setIcon(newImage);
                    }}
                    catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
           }
               else
               if(id.charAt(0)=='S'||id.charAt(0)=='s'){
               
                    try{
                con=DriverManager.getConnection(url,uid,pass);
               stmt=con.createStatement();
               stmt.executeQuery("use ssm1");
                    rs=stmt.executeQuery("select * from student where id='"+id+"'");
                   
                    while(rs.next()){
                          jTextField1.setText(rs.getString(1));
                        jTextField2.setText(rs.getString(2));
                        boolean s=false;
                        if(rs.getBoolean(14)==true){
                            jCheckBox1.setSelected(true);
                            jComboBox1.setEnabled(true);
                            jTextField4.setEnabled(true);
                       int status=rs.getInt(15); 
                       jComboBox1.setSelectedIndex(status);
                        jTextField4.setText(rs.getString(7));
                      
                        
                        }  if(rs.getBoolean(4)==false)
                            jRadioButton2.setSelected(true);
                        else
                            jRadioButton1.setSelected(true);
                        
                         
                        byte[] image=rs.getBytes(8);
                      ImageIcon image1=new ImageIcon(image);
                      Image im=image1.getImage();
                      Image myImg=im.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(),Image.SCALE_SMOOTH);
                      ImageIcon newImage=new ImageIcon(myImg);
                      jLabel5.setIcon(newImage);
                   
                    }}
                    catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
               }
                   else
                   if(id.charAt(0)=='E'||id.charAt(0)=='e')
                       {
                            try{
                con=DriverManager.getConnection(url,uid,pass);
               stmt=con.createStatement();
               stmt.executeQuery("use ssm1");
                    rs=stmt.executeQuery("select * from staff where id='"+id+"'");
                   
                    while(rs.next()){
                          jTextField1.setText(rs.getString(1));
                        jTextField2.setText(rs.getString(2));
                        boolean s=false;
                        if(rs.getBoolean(11)==true){
                            jCheckBox1.setSelected(true);
                            jComboBox1.setEnabled(true);
                            jTextField4.setEnabled(true);
                       int status=rs.getInt(12); 
                       jComboBox1.setSelectedIndex(status);
                        jTextField4.setText(rs.getString(4));
                      
                        
                        }  if(rs.getBoolean(9)==false)
                            jRadioButton2.setSelected(true);
                        else
                            jRadioButton1.setSelected(true);
                        
                         
                        byte[] image=rs.getBytes(6);
                      ImageIcon image1=new ImageIcon(image);
                      Image im=image1.getImage();
                      Image myImg=im.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(),Image.SCALE_SMOOTH);
                      ImageIcon newImage=new ImageIcon(myImg);
                      jLabel5.setIcon(newImage);
                   
                    }}
                    catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
                       }
       else
                       if(id.charAt(0)=='P'||id.charAt(0)=='p')
                       {
                            try{
                con=DriverManager.getConnection(url,uid,pass);
               stmt=con.createStatement();
               stmt.executeQuery("use ssm1");
                    rs=stmt.executeQuery("select * from parti where id='"+id+"'");
                   
                    while(rs.next()){
                          jTextField1.setText(rs.getString(1));
                        jTextField2.setText(rs.getString(2));
                        boolean s=false;
                        if(rs.getBoolean(11)==true){
                            jCheckBox1.setSelected(true);
                            jComboBox1.setEnabled(true);
                            jTextField4.setEnabled(true);
                       int status=rs.getInt(12); 
                       jComboBox1.setSelectedIndex(status);
                        jTextField4.setText(rs.getString(13));
                      
                        
                        }  if(rs.getBoolean(10)==false)
                            jRadioButton2.setSelected(true);
                        else
                            jRadioButton1.setSelected(true);
                        
                         
                        byte[] image=rs.getBytes(8);
                      ImageIcon image1=new ImageIcon(image);
                      Image im=image1.getImage();
                      Image myImg=im.getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(),Image.SCALE_SMOOTH);
                      ImageIcon newImage=new ImageIcon(myImg);
                      jLabel5.setIcon(newImage);
                   
                    }}
                    catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
                       }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con=null;
 Statement stmt=null;
 ResultSet rs=null;
 String a[]=connectivity.file();
 String one=jTextField1.getText();
 String two=jTextField2.getText();
 boolean three=false;
 int four=-1;
 if(jCheckBox1.isSelected())
     three=true;
 else
     three=false;
 if(three==false)
     four=-1;

 else
     four=jComboBox1.getSelectedIndex();
  String five=jTextField4.getText();
 int six=0;
 if(jRadioButton1.isSelected()==true)
     six=1;
 String seven=jTextArea1.getText();
              
        if(six==1)
         connectivity.executeQU("insert into in_out values('"+one+"','"+two+"',null,'"+five+"','"+four+"','"+seven+"',1)", a);
         else
            connectivity.executeQU("insert into in_out values('"+one+"','"+two+"',null,'"+five+"','"+four+"','"+seven+"',0)", a);
       String id=jTextField1.getText();
       if(id.charAt(0)=='w'||id.charAt(0)=='W')
       {if(six==1)
           connectivity.executeQU("update worker set status=1 where id='"+id+"'", a);
           else
           connectivity.executeQU("update worker set status=0 where id='"+id+"'", a);
          
       }
       else
           if(id.charAt(0)=='V'||id.charAt(0)=='v')
           {
             if(six==1)
           connectivity.executeQU("update visitor set status=1 where id='"+id+"'", a);
           else
           connectivity.executeQU("update visitor set status=0 where id='"+id+"'", a);
          
              
           }
               else
               if(id.charAt(0)=='S'||id.charAt(0)=='s'){
               
                 if(six==1)
           connectivity.executeQU("update student set status=1 where id='"+id+"'", a);
           else
           connectivity.executeQU("update student set status=0 where id='"+id+"'", a);
          
               }
                   else
                   if(id.charAt(0)=='E'||id.charAt(0)=='e')
                       {
                           if(six==1)
           connectivity.executeQU("update staff set status=1 where id='"+id+"'", a);
           else
           connectivity.executeQU("update staff set status=0 where id='"+id+"'", a);
          
                       }
       else
                       if(id.charAt(0)=='P'||id.charAt(0)=='p')
                       {
                         if(six==1)
           connectivity.executeQU("update parti set status=1 where id='"+id+"'", a);
           else
           connectivity.executeQU("update parti set status=0 where id='"+id+"'", a);
          
                       }
       JOptionPane.showMessageDialog(this,"Entry Successful!");
       this.dispose();
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
