/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Scanner;
import newpackage.connectivity;


/**
 *
 * @author vibhumprakash
 */
public class frame1 extends javax.swing.JFrame {
        public static boolean status;
        public static boolean admin=false;
        public static String id[]=new String[3];
         static String aa="",ab="";
    /**
     * Creates new form frame1
     */
    public frame1(boolean s) {this.setTitle("Sign In");
        this.setSize(420, 370);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("culogo.png"));
        initComponents();status =s;
        if(s==false){this.setTitle("First Time Sign Up");jButton1.setText("SignUp");jButton2.setText("Clear");}
        
        
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(29, 85, 166));
        setMinimumSize(new java.awt.Dimension(449, 350));
        setPreferredSize(new java.awt.Dimension(449, 350));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(82, 85, 104, 25);

        jLabel2.setFont(new java.awt.Font("SimSun", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Passcode");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(82, 137, 104, 29);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 240, 120, 40);

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(218, 90, 190, 30);

        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html><body><center><h1><font color=\"BLACK\">A</font><font color=\"RED\">V Corp</font></h1></center><body");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 13, 396, 46);

        jPasswordField1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(218, 144, 190, 30);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Cancel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 240, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean flag=false;
        if(status==true){
                         String a=jTextField1.getText();
                         String aa="",ab="";String ac="";
        String b=new String(jPasswordField1.getPassword());
        Connection con;
        Statement stmt;
        
        id=connectivity.file();
        try{
                    
                    
                    
                    con=DriverManager.getConnection("jdbc:mysql://localhost:"+id[0]+"/ssm1",id[1],id[2]);
                    stmt=con.createStatement();
                    ResultSet rs;
                    rs=stmt.executeQuery("select * from author;");
                    
                    while(rs.next())
                    {   
                        aa=rs.getString(1);
                        ab=rs.getString(2);
                        ac=rs.getString(4);
                         if( a.equals(aa)&&b.equals(ab))
        { 
            frame0.usr=aa;frame0.pass=ab;                       //storing usr and pass into the main frame
            if(ac.equals("1")){this.admin=true;}
           
                  
           frame0.admin=this.admin;
           frame0 s=new frame0();
           s.usr=aa;
           s.pass=ab;
           s.fun(); 
           s.setVisible(true);
         
          
           connectivity co=new connectivity();
           
        
           
           flag=true;
           this.dispose();
           break;
        }
                    }
                    
                      
                
       
       
        if(flag==false){
             int n=JOptionPane.showConfirmDialog(null, "Your Entered Wrong Credential! \nYou Want to Retry?","Error!",JOptionPane.YES_NO_OPTION);
            if(n==JOptionPane.YES_OPTION)
            {jTextField1.setText("");
             jPasswordField1.setText("");}
            if(n==JOptionPane.NO_OPTION)
            System.exit(0);
                }}
       catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}

        
        
        }
        
        
        
        
if(status==false)
{
  String a=jTextField1.getText();
  
     
       String b=new String(jPasswordField1.getPassword());
       if(a.length()<8&b.length()<8)
           JOptionPane.showMessageDialog(this, "Username or Pass lenght is less than 8");
       else{
       Connection con;
       Statement stmt;
      

connectivity c=new connectivity();
id=connectivity.file();


       
        try{      
                      
               
             int n=JOptionPane.showConfirmDialog(null, "Are you sure?","Confirm",JOptionPane.YES_NO_OPTION);
            if(n==JOptionPane.YES_OPTION)
            {
          con=DriverManager.getConnection("jdbc:mysql://localhost:"+id[0]+"/ssm1",id[1],id[2]);
                    stmt=con.createStatement();
                    ResultSet rs;
                  connectivity.executeQU("delete from author where pass='admin';",id);
                    stmt.executeUpdate("insert into author(usr,pass,admin) values('"+a+"','"+b+"','1');");
                    frame0.admin=true;
                    frame0 fr=new frame0();
                    fr.fun(); fr.setLocation(connectivity.getx(fr.getWidth()), connectivity.gety(fr.getHeight()));
                    fr.setVisible(true);
                    this.dispose();
                    
                   
        
            }
            
            if(n==JOptionPane.NO_OPTION)
            System.exit(0);
            
            
            
                }
       catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
              
        

        
  
    
    
    


}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(status==true)
        System.exit(0);
        if(status==false)
        {        jTextField1.setText("");
                 jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
