

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.DriverManager;
import java.sql.ResultSet;
import newpackage.connectivity;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.sql.*;
import java.util.Set;
import java.util.TreeMap;
import javafx.scene.control.Cell;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Guru
 */
public class frame0 extends javax.swing.JFrame {
    static String usr,pass;
public static boolean admin=false;
public  void fun1(){
     
      
    Thread t;
    t = new Thread(){
        @Override
    public void run(){
        
        for(;;){
            jMenu2.setText("                                                                  "
                    + "                                                                       "
                    + "                                                                        "
                    + "                                                         "+new Date().toString());
            try{
                Thread.sleep(1000);}
                catch(InterruptedException e){
                    System.out.println(e.getMessage());}}}};
                
                t.start();}

public void fun(){ if(this.admin==true){jMenuItem3.setEnabled(true);jMenu5.setEnabled(true);}
                     if(this.admin==false){jMenu5.setEnabled(false);jMenuItem3.setEnabled(false);user.setEnabled(false);}
                       jMenuItem10.setText(this.usr);
                     
                        }
                    
                     
    /**
     * Creates new form frame0
     */
public void count(){
 Connection con=null;
 Statement stmt=null;
 ResultSet rs=null;
 String a[]=connectivity.file();
 String uid=a[1],pass=a[2];
                    String url="jdbc:mysql://localhost:"+a[0];try{
                con=DriverManager.getConnection(url,uid,pass);
               stmt=con.createStatement();
               stmt.executeQuery("use ssm1");
                    rs=stmt.executeQuery("select * from in_out;");
                   int i=0;
                    while(rs.next()){
                      i++;
                   
                    }
                   
                    }
                    catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
}
    public frame0() {    
        
        hints h=new hints();
        h.setSize(410, 320);
        this.setTitle("The GateKeeper");
             this.fun1();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("culogo.png")); 
       
        h.setLocation(connectivity.getx(h.getWidth()),connectivity.gety(h.getHeight()) ); 
    h.setVisible(true); 
    h.s=true; 
        initComponents();
       getContentPane().setBackground(new Color(0,153,153));
        this.fun1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        user = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setMinimumSize(new java.awt.Dimension(1920, 1090));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1015, 835, 344, 87);

        jPanel1.setBackground(new java.awt.Color(94, 108, 108));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 0, 102));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(590, 140, 712, 376);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1080);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(820, 140, 708, 370);

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(400, 32769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(355, 50));

        jMenu1.setBackground(new java.awt.Color(0, 102, 102));
        jMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("  File  ");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu1.setOpaque(true);

        jMenuItem3.setText("Drop Database");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu8.setBackground(new java.awt.Color(0, 102, 102));
        jMenu8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu8.setForeground(new java.awt.Color(255, 255, 255));
        jMenu8.setText("  Visitors  ");
        jMenu8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu8.setOpaque(true);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Visitors List");
        jMenuItem12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenuBar1.add(jMenu8);

        jMenu4.setBackground(new java.awt.Color(0, 102, 102));
        jMenu4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("  Admin  ");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu4.setOpaque(true);

        jMenu5.setText("Users");
        jMenu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem8.setText("Add");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem9.setText("Delete");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenu4.add(jMenu5);

        jMenu6.setText("Change Password");
        jMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        user.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        user.setText("Others");
        user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jMenu6.add(user);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuItem10.setText("Current");
        jMenuItem10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenu4.add(jMenu6);

        jMenuBar1.add(jMenu4);

        jMenu3.setBackground(new java.awt.Color(0, 102, 102));
        jMenu3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("  Settings  ");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu3.setOpaque(true);

        jMenuItem4.setText("Port");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu12.setBackground(new java.awt.Color(0, 102, 102));
        jMenu12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu12.setForeground(new java.awt.Color(255, 255, 255));
        jMenu12.setText("IN-OUT");
        jMenu12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu12.setOpaque(true);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setText("Log Table");
        jMenuItem15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem15);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Entry");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem6);

        jMenuBar1.add(jMenu12);

        jMenu7.setBackground(new java.awt.Color(0, 102, 102));
        jMenu7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setText("  Events  ");
        jMenu7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu7.setOpaque(true);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem11.setText("Events list");
        jMenuItem11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem11);

        jMenuBar1.add(jMenu7);

        jMenu11.setBackground(new java.awt.Color(0, 102, 102));
        jMenu11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu11.setForeground(new java.awt.Color(255, 255, 255));
        jMenu11.setText("Messages");
        jMenu11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu11.setOpaque(true);
        jMenu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu11ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Notifications");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem5);

        jMenuBar1.add(jMenu11);

        jMenu10.setBackground(new java.awt.Color(0, 102, 102));
        jMenu10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu10.setForeground(new java.awt.Color(255, 255, 255));
        jMenu10.setText("  Help  ");
        jMenu10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenu10.setOpaque(true);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("Hint");
        jMenuItem14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem14);

        jMenuBar1.add(jMenu10);

        jMenu2.setBackground(new java.awt.Color(0, 102, 102));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("                                                                                                                                                                                                                                          ");
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMenu2.setOpaque(true);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        
   new hints().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.out.print(pass);
        String m =(String)JOptionPane.showInputDialog(null, "Enter Admin Passcode :",
                "Passcode");
        System.out.println(m+"ok");
       
        if(pass.equals(m)){
        logo k=new logo();
        k.setTitle("Initializing tables");
        String q[]={"he","llo"};        //formality for calling main
        logo.main(q);}
        
        else 
            JOptionPane.showMessageDialog(this,"You Entered wrong Password");
       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id=jTextField1.getText();
        new search(id.trim());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    new usr(true).setVisible(true);
    
      
      
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        String s=JOptionPane.showInputDialog(this,"Enter the UserName");
        String id[]=connectivity.file();
        try{
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:"+id[0]+"/ssm1",id[1],id[2]);
                   Statement  stmt=con.createStatement();
                    ResultSet rs;
                    rs=stmt.executeQuery("select * from author where usr='"+s+"';");
                    usr f=new usr(false);
                    
                    while(rs.next()){
                    f.a=rs.getString(1);
                    f.b=rs.getString(2);
                    if(rs.getString(4)=="0")
                        f.c=false;
                    else
                        f.c=true;
                    f.setVisible(true);
                    }
        }catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
        String s=JOptionPane.showInputDialog(this,"Enter the username");
       Connection con=null;
 Statement stmt=null;
 String a[]=connectivity.file();
 String uid=a[1],pass=a[2];
                    String url="jdbc:mysql://localhost:"+a[0]+"/ssm1";try{
                con=DriverManager.getConnection(url,uid,pass);
               stmt=con.createStatement();
               
                    ResultSet rs;
                    rs=stmt.executeQuery("Select * from author where usr='"+s+"';");
                   
                    while(rs.next()){
                    usr1.a=rs.getString(1);
                    usr1.b=rs.getString(2);
                    if(rs.getString(4)=="1")
                        usr1.c=true;
                    else
                        usr1.c=false;
                    }
                    usr1 us=new usr1();
                    us.setVisible(true);
                    
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null,e.getMessage());}
      
    }//GEN-LAST:event_userActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        String s=JOptionPane.showInputDialog(this,"Enter the Passcode:");
        boolean f=connectivity.executeQU("update author set pass='"+s+"' where usr='"+frame0.usr+"';", connectivity.file());
        if(f==true){JOptionPane.showMessageDialog(this,"Updated Successfully ");}else JOptionPane.showMessageDialog(this,"Can't Update ");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        String pass=JOptionPane.showInputDialog(this,"Enter the Password");
        if(this.pass.equals(pass)){
        String port=JOptionPane.showInputDialog(this,"Enter the Port Number");
        
        String[] id=connectivity.file();
         BufferedWriter bw = null;
		FileWriter fw = null;

		try {

			String content = port+"\n"+id[1]+"\n"+id[2];

			fw = new FileWriter("port.txt");
			bw = new BufferedWriter(fw);
			bw.write(content);
                        JOptionPane.showMessageDialog(this,"Successfully Changed");
		

		} catch (IOException e) {

			JOptionPane.showMessageDialog(this, e.getMessage());

		} finally {

			try {

				if (bw != null)
					bw.close();

				if (fw != null)
					fw.close();

			} catch (IOException ex) {JOptionPane.showMessageDialog(this, ex);
			}

		}
        }
        else
            JOptionPane.showMessageDialog(this,"You Entered Wrong Passcode");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
      Connection con=null;
 Statement stmt=null;
 ResultSet rs=null;
 String a[]=connectivity.file();
 String uid=a[1],pass=a[2];
                    String url="jdbc:mysql://localhost:"+a[0];try{
                con=DriverManager.getConnection(url,uid,pass);
               stmt=con.createStatement();
               stmt.execute("use ssm1");
                    rs=stmt.executeQuery("select * from events");
                   table t1=new table(rs);
                   t1.setVisible(true);
                    
                    
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        visitor v=new visitor();
       
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu11ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jMenu11ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        new log().setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new notification().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new entry().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       frame0 k= new frame0();
      
       k.setVisible(true);
         

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem user;
    // End of variables declaration//GEN-END:variables
}
