/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Guru
 */
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import newpackage.connectivity;
public class hints extends javax.swing.JFrame {
static public String tips[]=new String[10];
static public String img[]={"one.png","two.png","three.png","four.png","five.png","six.png","seven.png","eight.png","nine.png","ten.png"};

static public int count=0;
static public boolean s=false;
    /**
     * Creates new form hints
     */
    public hints() {
        this.setSize(410,300);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("culogo.png"));
        
        this.setTitle("Hints");
        initComponents();
        

jButton1.setOpaque(false);
jButton1.setContentAreaFilled(false);
jButton1.setBorderPainted(false);

jButton2.setOpaque(false);
jButton2.setContentAreaFilled(false);
jButton2.setBorderPainted(false);
        tips[0]="<html>To Revisit Help Menu</html>";
        tips[1]="To check Notification";
        tips[2]="Check Out Current Events";
        tips[3]="In-Out Log Entry";
        tips[4]="Change Port Number for Database";
        tips[5]="Include or Debar New Users";
        tips[6]="Check Visitor's List";
        tips[7]="Drop Whole Data To Dump";
        tips[8]="<html>Forgot to SignUp After Drop <br>Login With admin-admin</html>";
        tips[9]="Search Entries from Search Bar";
        jLabel2.setText(tips[count]);
        
        ImageIcon imgThisImg = new ImageIcon(img[count]);
        jLabel1.setIcon(imgThisImg);
        Image i=null;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(410, 320));
        setPreferredSize(new java.awt.Dimension(410, 320));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("<html>B<br>a<br>c<br>k</html>\n");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(12, 39, 41, 146);

        jButton2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("<html>N<br>e<br>x<br>t</html>\n");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(341, 42, 41, 146);

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(89, 13, 234, 200);

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(18, 226, 380, 61);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-110, 0, 680, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        


         if(count==9){
            jButton2.setEnabled(false);
            jLabel2.setText(tips[count]);
            ImageIcon imgThisImg = new ImageIcon(img[count]);
            jLabel1.setIcon(imgThisImg);
         }
        else{count++;
            jButton1.setEnabled(true);
            jLabel2.setText(tips[count]);
            ImageIcon imgThisImg = new ImageIcon(img[count]);
            jLabel1.setIcon(imgThisImg);
            
       
         } 
             
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(count==0){count++;
            jButton1.setEnabled(false);jLabel2.setText(tips[count]);
            ImageIcon imgThisImg = new ImageIcon(img[count]);
            jLabel1.setIcon(imgThisImg);
        }
        else{count--;
            jButton2.setEnabled(true);
            jLabel2.setText(tips[count]);
            ImageIcon imgThisImg = new ImageIcon(img[count]);
            jLabel1.setIcon(imgThisImg);
            
       
         } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hints().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
